export const APPOINTMENTS_REQUEST_STARTED = "APPOINTMENTS_REQUEST_STARTED";
export const APPOINTMENTS_FAILURE = "APPOINTMENTS_FAILURE";
export const LISTEN_APPOINTMENTS_SUCCESS = "LISTEN_APPOINTMENTS_SUCCESS";
export const APPOINTMENTS_UNLOAD = "APPOINTMENTS_UNLOAD";
