export const USER_REQUEST_STARTED = "USER_REQUEST_STARTED";
export const USER_SET = "USER_SET";
export const USER_UNSET = "USER_UNSET";
export const USER_FAILURE = "USER_FAILURE";
export const USER_VERIFICATION_SENT = "USER_VERIFICATION_SENT";
